### ISSUE TITLE
2020Q3 - 4.3 Android Components Report Site Issue parity work

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#149] opened 2020-06-29 20:32 UTC
Tracking Bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1643132

This KR tracks the following issues:

* [x] [Bug 1645844](https://bugzilla.mozilla.org/show_bug.cgi?id=1645844): Add `browser-foo` to `extra_labels` so we can track product funnel
* [x] [Bug 1643147](https://bugzilla.mozilla.org/show_bug.cgi?id=1643147): Enable automated screenshots 
* [x] [Bug 1643148](https://bugzilla.mozilla.org/show_bug.cgi?id=1643148): Ship the `tabExtrasActor` for more details reports

**Comment by denschub** [comment] 2020-07-21 13:04
I started on the tabActor work, but no real progress yet since I was on PTO. :)

**Comment by denschub** [comment] 2020-08-04 12:39
Did some re-prioritization inspired by Ksenia asking for a proper "Fenix" label to improve her statistics. That feature is implemented, and I'm currently writing some in-tree (as in inside android-components) tests for that one.

**Comment by denschub** [comment] 2020-08-18 11:31
I have identified a path to take, but unfortunately the meeting to properly discuss this hasn't happened yet because of reasons(tm). I'm poking folks, but my main point of contact is OOO this week, so I'll most likely just draft everything into an email and throwing that into the fenix team's inbox.

**Comment by denschub** [comment] 2020-09-01 13:00
Got A-C tests for both components working (yay!), and am working on tests inside Fenix, which appear to be a lot simpler, because there is an actual app to be tested. I also accidentally built screenshots into the Fenix reporter, so that's another "done" once that patch lands (hopefully that's in a couple of days).

**Comment by denschub** [comment] 2020-09-11 17:08
Code that's adding screenshots, adding all the `tabExtrasActor` magic, as well as tests for both our components is, in theory, ready to land: https://github.com/mozilla-mobile/android-components/compare/master...denschub:webcompat-features-work

Unfortunately, I ... can't land that, because `tabs.captureVisibleTab()` broke on mobile 17 days ago [due to some Fission work](https://bugzilla.mozilla.org/show_bug.cgi?id=1636508) and nobody noticed until I tested my things in Fenix. :agi was very helpful in debugging this, and this regression is tracked in https://bugzilla.mozilla.org/show_bug.cgi?id=1664522, which is now blocking this task.

**Comment by denschub** [comment] 2020-09-22 20:24
https://github.com/mozilla-mobile/android-components/pull/8448 is merged. This means that the feature-complete reporter will ship in android-components 61, so it should be in Fenix Nightly in 2 weeks or so. My work here is done.

**Closed as completed** 2021-01-11 04:43 UTC
Labels: Complete
