### ISSUE TITLE
2019-Q1 4.1 - Performance improvements to webcompat.com

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#61] opened 2018-12-10 22:00 UTC
* time estimate: 3 months

**Comment by marimeireles** [comment] 2019-01-21 22:40
* Finished measurements related to the server;
* Tried to improve XHR loading but got to the conclusion that's not worthwhile or maybe not even possible;
* Fixed the test mode bug;
* Finished blog post;
* Started to try to render the server using python instead of relying on js only, ran some tests. Didn't get any meaningful result, so I'll try to adapt more code to see if it has an improvement;

**Comment by marimeireles** [comment] 2019-01-25 13:02
* Fix code bug

**Comment by marimeireles** [comment] 2019-02-12 11:37
* Using flask-firehose to make pushes from python;
* Tested webcompat.com security;
* Finished what I had planned to render in python but there are some architecture problems that need to be fixed in order to land it.

**Comment by marimeireles** [comment] 2019-02-19 13:55
* Fixed all regressions caused by Markdown-it;
* Optimized our use of Favicons;
* Added a few improvements to how we render text.

**Comment by marimeireles** [comment] 2019-02-26 13:12
* Testing which is the best way to compress stuff;
* Testing if we should fetch fonts from our server instead of google's;
* Trying to fix the one last regression bug.

**Comment by miketaylr** [comment] 2019-03-12 13:21
Update: let's call this done! 🎉 🐕

**Closed** 2019-04-08 21:05 UTC
Labels: Complete, Score: 0.7
