### ISSUE TITLE
2019Q4 - 1.4 Diagnosis all coda.io bugs

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#101] opened 2019-10-01 09:01 UTC
We should diagnose all coda.io bugs to the point of understanding what (duplicate) core issues exist, or need to be reported. The deliverable here should be a 1 or 2 page document containing a summary with pointers to core issues.

**Comment by miketaylr** [comment] 2019-10-01 11:59
Here is the writeup of the known bugs: https://docs.google.com/document/d/1pNLQeIhVTwvHeoe_QepucSH8KP093x_8nD5wZwD6XdU/edit#

Username and password for the login can be grabbed from our SoftVision crew.

**Comment by wisniewskit** [comment] 2019-10-15 18:50
I just diagnosed the issues on the doc. Note that I tested today's nightly build of Firefox (71a1, 2019-10-15).

---
### Different fonts used

Confirmed. The CSS being used for the text highlighted by the screenshot (and a lot more):

`font-family: system-ui, sans-serif`

Firefox does not yet support `system-ui` ([bz1226042](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042)), unlike Chrome.

So this is a dupe of that issue.

Note that this will be system-specific: for me on Linux and MacOS, both browsers choose the same fonts (Liberation Sans and Helvetica), but on Windows 10 Chrome ends up picking Segoe UI while Firefox picks Arial.

---

### The buttons from the header are not visible when the window is narrow

Works for me on Linux, MacOS and Windows 10. The menu bar shown in the screenshot wraps similarly in Firefox and Chrome (it does not visually go off the side of the screen until the same point where the same thing happens in Chrome).

---

### Text is not wrapped

Works for me on Linux, MacOS and Windows 10. The header text shown in the screenshot wraps similarly in Firefox and Chrome.

---

### Table is not aligned

Works for me on Linux, MacOS and Windows 10. The table shifts closer to the left when the window becomes too narrow, otherwise it is shifted a bit to the right (in both Chrome and Firefox).

---

### Popups are not dismissed when clicking outside them

Works for me on Linux, MacOS and Windows 10. Just like in Chrome, the right-click context menu popups are dismissed when I click elsewhere on the page, but not when I click on the browser's user interface elements.

---

### Unable to type

Confirmed. I can type, but when I click away, my changes are reverted unless they were a deletion of a bit of selected text, or just the first character that I typed to replace a selection.

An error is shown in the console as I type, because a variable `this._cachedInputData` is undefined when their `onInput` handler is called. It turns out that variable is set `onBeforeInput`, which is not implemented in Firefox yet ([bz970802]).

It seems I can fix this (or at least hack it to appear to be working) by changing this line in [this script](https://cdn.coda.io/assets/browser.3cc8e311cdb39c548962.entry.js):
```
            const {anchorOffset: n, data: r, inputType: o, replacementCursor: i} = Object(p["d"])(this._cachedInputData);
```

To this:
```
            const {anchorOffset: n, data: r, inputType: o, replacementCursor: i} = Object(p["d"])(this._cachedInputData || this.getInputData(t));
```

But I can't really tell if that's a sufficient fix for this specific issue or not. Still this could indicate that an easy work around exists until Firefox supports `beforeinput`.

---

### Unable to select small amounts of text or images

Works for me on Linux, MacOS and Windows 10. I can double-click to select text and images just as I can in Chrome (and also click and drag or use the keyboard to make a selection).

---

### No horizontal scrolling

Works for me on Linux, MacOS and Windows 10. There is a scrollbar visible when the page is narrow enough, and I can drag the scrollbar or use two-finger touchpad dragging to scroll the view horizontally, just as I can in Chrome.

---

### Double scrollbar displayed

I could not reproduce on Linux, MacOS and Windows 10, with multiple zoom levels on the document. It appears that the "empty" spot to the right of the document's scrollbar is a `<div>` with CSS that implies it is meant to be for comments. But unless there is another element which appears there when the second scrollbar is visible, I cannot tell why it would ever show a scrollbar if there are no actual comments there. In fact they even seem to use `scrollbar-width: none` in their CSS, so perhaps this is something they recently fixed?

---

### Typed text is not saved

This is a dupe of the "unable to type" issue diagnosed above (the same console errors appear, and the hack/fix above fixes this as well).

---

# Summary

Coda.io relies on `beforeinput` events, which may be easy to work around (or maybe not). They also use the `system-ui` CSS font-family, which causes some differences in font choices. I could otherwise not reproduce the problems shown.

Note that I also see them using CSS zoom in their `browser.css`, which could mean that some icons end up being smaller in Firefox than Chrome:

```
.parts_bin--iconBoxLarge--2Jk_zOy5 {
  zoom: 1.5;
}
.parts_bin--templateIconWrap--kkckJkQv.parts_bin--isPreview--2g5KjVw0 {
  zoom: 1.5;
}
```

**Comment by wisniewskit** [comment] 2019-10-16 14:01
Probably worth noting that issue https://github.com/webcompat/web-bugs/issues/15276 also seems fixed on their end now. I'll mark this as complete for now, since it looks like we're done here.

**Comment by miketaylr** [comment] 2019-10-24 16:28
https://twitter.com/AdamOpenWeb/status/1187390706546950144

It sounds like Firefox is officially supported now. 🎈

**Closed as completed** 2020-01-06 22:55 UTC
Labels: Complete
