### ISSUE TITLE
2018-Q2 3.1 Create and land a web extension for spoofing UA string on Google and Facebook

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#12] opened 2018-04-30 23:10 UTC
* [Bug 1453691](https://bugzilla.mozilla.org/show_bug.cgi?id=1453691)

**Comment by wisniewskit** [comment] 2018-05-14 22:14
Feedback has been received on how to proceed with this, though I haven't had time to investigate it during this OKR sprint. Confidence remains the same for now.

**Comment by wisniewskit** [comment] 2018-05-25 14:32
Quick update: we're still waiting on a blocking bug to land, but once that's done, only minor work apparently remains on the actual addon itself. Unfortunately it's uncertain whether the blocking bug will land soon enough for us to actually land the addon by the end of the quarter.

**Comment by wisniewskit** [comment] 2018-05-29 15:13
The blocking bug has since landed and I have completed development of the addon. It's now pending any remaining reviews, so my confidence here has increased that we can get it shipped this quarter.

**Comment by wisniewskit** [comment] 2018-06-04 23:43
We've now landed this, but unfortunately Fennec system addons are not being built, and I don't have the buildsystem know-how to easily figure out why. I've created [bz1466539](https://bugzilla.mozilla.org/show_bug.cgi?id=1466539) to figure it out, but kmag is on PTO until tomorrow, so I can't estimate how long it will take to tackle this final blocker.

**Comment by miketaylr** [comment] 2018-06-06 20:32
Update: @wisniewskit has a patch up that is waiting on review.

**Comment by miketaylr** [comment] 2018-06-07 15:42
Update: patch bounced, waiting on feedback.

**Comment by wisniewskit** [comment] 2018-06-14 16:42
The addon has actually landed in moz-central, but is not actually being bundled with Fennec due to build-system issues ([bz1466539](https://bugzilla.mozilla.org/show_bug.cgi?id=1466539)). There are also potential mysterious performance test regressions noted in that bug. I'm no longer sure how confident to be about shipping anytime soon as a result, and it seems out of my hands.

**Comment by denschub** [comment] 2018-06-26 13:15
Still blocked, unfortunately.

**Comment by wisniewskit** [comment] 2018-06-29 15:28
This just landed today, thanks to kmag's noble efforts in [bz1459004](https://bugzilla.mozilla.org/show_bug.cgi?id=1459004). We're done here!

**Closed by wisniewskit** 2018-06-29 15:28 UTC
Labels: DONE

**Comment by miketaylr** [comment] 2018-07-02 16:44
Score: 1.0

This snuck in at the end of the quarter after being blocked on some build issues. We plan on letting this ship for 4 weeks, then planning next steps. (In retrospect, we probably should have written another KR for writing up findings… but we didn’t. And we don’t have any right now).
