### ISSUE TITLE
QA Triage Trends

### ISSUE THREAD

**Issue by softvision-oana-arbuzov** [mozilla/webcompat-team-okrs#262] opened 2022-07-12 13:13 UTC
Gather & describe Webcompat issue where we spot patterns/trends while performing Triage. 

@janodvarko keep in the loop.

**Comment by softvision-oana-arbuzov** [comment] 2022-07-12 14:47
Our current findings: 
- there are a lot of duplicates for [m.imgur.com](https://m.imgur.com/a/2ZpeEzF) site - in Private Mode the site does not load 
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1742344
=> there is a patch for patch https://phabricator.services.mozilla.com/D150034

- another issue with a few duplicates is related to Facebook news feed - keeps jumping and skips posts: 
Webcompat bug: https://github.com/webcompat/web-bugs/issues/106716 

- an important issue - Photoshop is unsupported in Firefox - work in progress
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1738201

- embedded YouTube video "Share" button is not functional
Webcompat bugs: https://github.com/webcompat/web-bugs/issues/107286, https://github.com/webcompat/web-bugs/issues/105859, https://github.com/webcompat/web-bugs/issues/106938

- there are a lot of reports about Business Apple not being supported on Firefox
Webcompat bug: https://github.com/webcompat/web-bugs/issues/18964
Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1741576

**Comment by softvision-raul-bucata** [comment] 2022-07-18 14:05
Another issue with a few duplicates is related to Google Meet broken audio in calls:
 - `webcompat`: https://github.com/webcompat/web-bugs/issues/107298, https://github.com/webcompat/web-bugs/issues/107054, https://github.com/webcompat/web-bugs/issues/107098
 - `Bugzilla`: https://bugzilla.mozilla.org/show_bug.cgi?id=1666866, https://bugzilla.mozilla.org/show_bug.cgi?id=1653112,https://bugzilla.mozilla.org/show_bug.cgi?id=1666866, https://bugzilla.mozilla.org/show_bug.cgi?id=1670633

**Comment by softvision-raul-bucata** [comment] 2022-07-25 14:48
There are a lot of duplicates for web.whatsapp.com not loading in PRIVATE MODE:
- `webcompat`: https://github.com/webcompat/web-bugs/issues/107832, https://github.com/webcompat/web-bugs/issues/107819, https://github.com/webcompat/web-bugs/issues/107352, https://github.com/webcompat/web-bugs/issues/107250, https://github.com/webcompat/web-bugs/issues/106867

- `Bugzilla`: https://bugzilla.mozilla.org/show_bug.cgi?id=1767407

This issue is also reproducible if the "Delete history" option is enabled or "Delete cookies and site data when Firefox is closed" is enabled or any other setting that will cause the browser to behave like in private browsing mode.

**Comment by softvision-raul-bucata** [comment] 2022-07-29 11:16
It seems that the print preview is broken for some sites in Firefox, as we had a couple of reports regarding this, on desktop:
- https://github.com/webcompat/web-bugs/issues/107778 - reproducible
- https://github.com/webcompat/web-bugs/issues/107901 - reproducible
- https://github.com/webcompat/web-bugs/issues/108135 - Needs more info (paid account needed)
- https://github.com/webcompat/web-bugs/issues/108247 - Paid account needed
- https://github.com/webcompat/web-bugs/issues/108605 - No valid link to the PDF
- https://github.com/webcompat/web-bugs/issues/109694 - No valid link to the PDF 

update 02/09/2022

Some new reports about Print Preview (browser feature) rendering the print preview page broken:
- https://github.com/webcompat/web-bugs/issues/110044
- https://github.com/webcompat/web-bugs/issues/110125
- https://github.com/webcompat/web-bugs/issues/109986
- https://github.com/webcompat/web-bugs/issues/109851
- https://github.com/webcompat/web-bugs/issues/110873
- https://github.com/webcompat/web-bugs/issues/111002
- https://github.com/webcompat/web-bugs/issues/111387
- https://github.com/webcompat/web-bugs/issues/111648 - banking account needed
- https://github.com/webcompat/web-bugs/issues/111651 - reproducible
- https://github.com/webcompat/web-bugs/issues/111887 - reproducible

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1269023 

For Android, we have this related issue in fenix : https://github.com/mozilla-mobile/fenix/issues/13214

**Comment by softvision-oana-arbuzov** [comment] 2022-07-29 11:48
In the past few days, some issues occurred for users in regards to scrolling the site being broken

- https://github.com/webcompat/web-bugs/issues/108126
- https://github.com/webcompat/web-bugs/issues/108125
- https://github.com/webcompat/web-bugs/issues/108101
- https://github.com/webcompat/web-bugs/issues/108104
- https://github.com/webcompat/web-bugs/issues/108103
- https://github.com/webcompat/web-bugs/issues/108633
- https://github.com/webcompat/web-bugs/issues/109287
- https://github.com/webcompat/web-bugs/issues/109286
- https://github.com/webcompat/web-bugs/issues/112379
- https://github.com/webcompat/web-bugs/issues/112380

Unfortunately, we were not able to reproduce any.

**Comment by softvision-oana-arbuzov** [comment] 2022-08-02 17:03
We received a few issues on Yahoo mail, and users were complaining that they are unable to perform different operations on emails (delete/reply/forward/attach files/archive/move/sort):
- https://github.com/webcompat/web-bugs/issues/108174 
- https://github.com/webcompat/web-bugs/issues/108249
- https://github.com/webcompat/web-bugs/issues/108207
- https://github.com/webcompat/web-bugs/issues/110756
- https://github.com/webcompat/web-bugs/issues/111333
- https://github.com/webcompat/web-bugs/issues/111358

**Comment by softvision-oana-arbuzov** [comment] 2022-08-05 11:35
We received a few issues on YouTube, and users complain they can't play random videos:
- https://github.com/webcompat/web-bugs/issues/108538 
- https://github.com/webcompat/web-bugs/issues/107863
- https://github.com/webcompat/web-bugs/issues/108528
- https://github.com/webcompat/web-bugs/issues/108295
- https://github.com/webcompat/web-bugs/issues/109955
- https://github.com/webcompat/web-bugs/issues/109678
- https://github.com/webcompat/web-bugs/issues/110035
- https://github.com/webcompat/web-bugs/issues/110058
- https://github.com/webcompat/web-bugs/issues/110049
- https://github.com/webcompat/web-bugs/issues/109417
- https://github.com/webcompat/web-bugs/issues/110078
- https://github.com/webcompat/web-bugs/issues/110583
- https://github.com/webcompat/web-bugs/issues/111072
- https://github.com/webcompat/web-bugs/issues/112027

Bugzilla issue:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1785149

Other reddit reports:

- https://old.reddit.com/r/firefox/comments/wthtet/youtube_videos_often_wont_load_and_otherwise_the/
- https://old.reddit.com/r/firefox/comments/wropka/firefox_struggling_to_open_some_youtube_videos/

**Comment by ksy36** [comment] 2022-08-11 03:40
There are 4 reports about Firefox being unsupported that share similar UI:

<img width="1691" alt="Screen Shot 2022-08-10 at 11 26 40 PM" src="https://user-images.githubusercontent.com/1303908/184060264-0a2bdbf8-0588-4560-81cf-7d5de510ed8f.png">


https://github.com/webcompat/web-bugs/issues/100131
https://github.com/webcompat/web-bugs/issues/101496
https://github.com/webcompat/web-bugs/issues/107833
https://github.com/webcompat/web-bugs/issues/107969

It looks like are built using the same platform from Entrata (property management software): https://www.entrata.com/marketing/prospect-portal. So there are likely more sites that are affected. We can add an intervention and investigate whether it's possible to find a solution that would cover domains that we don't know about.

**Comment by softvision-raul-bucata** [comment] 2022-08-19 14:30
There are some reports regarding the lower part of some pages being blacked out (some due to triggering the keyboard):
- https://github.com/webcompat/web-bugs/issues/109330
- https://github.com/webcompat/web-bugs/issues/109125
- https://github.com/webcompat/web-bugs/issues/108976
- https://github.com/webcompat/web-bugs/issues/108984
- https://github.com/webcompat/web-bugs/issues/109134
- https://github.com/webcompat/web-bugs/issues/109327
- https://github.com/webcompat/web-bugs/issues/109517

**Comment by softvision-oana-arbuzov** [comment] 2022-08-26 07:57
Users complain about videos on Twitch not being visible, unfortunately we were not able to reproduce them.
- https://github.com/webcompat/web-bugs/issues/109717
- https://github.com/webcompat/web-bugs/issues/109704
- https://github.com/webcompat/web-bugs/issues/109620
- https://github.com/webcompat/web-bugs/issues/109618
- https://github.com/webcompat/web-bugs/issues/106823
- https://github.com/webcompat/web-bugs/issues/109776
- https://github.com/webcompat/web-bugs/issues/109907
- https://github.com/webcompat/web-bugs/issues/109869
- https://github.com/webcompat/web-bugs/issues/109866
- https://github.com/webcompat/web-bugs/issues/109830
- https://github.com/webcompat/web-bugs/issues/109823

[Update] It seems that "Dark" theme was the culprit, a Bugzilla bug was reported: https://bugzilla.mozilla.org/show_bug.cgi?id=1788911

**Comment by softvision-oana-arbuzov** [comment] 2022-08-29 06:36
Users complain about graphical glitches, flickering, artifacts and freezes on sites using devices with Android 13, which don't occur on lower Android versions. 
- https://github.com/webcompat/web-bugs/issues/109777
- https://github.com/webcompat/web-bugs/issues/109673
- https://github.com/webcompat/web-bugs/issues/109690
- https://github.com/webcompat/web-bugs/issues/110266
- https://github.com/webcompat/web-bugs/issues/110308
- https://github.com/webcompat/web-bugs/issues/110113

We'll gather all the issues about this here and add the label Android 13. 
Currently, we don't own a device with Android 13, and tested in RDM, but we can't reproduce them.

[Update] I received the update to Android 13 on my Pixel 5, and re-checked all issues - none reproducible as described.

**Comment by softvision-oana-arbuzov** [comment] 2022-09-08 13:17
Dark mode/theme & Facebook container issues:
- Spiegel.de: https://github.com/webcompat/web-bugs/issues/110294
- Outlook Office: https://github.com/webcompat/web-bugs/issues/110474
- Twitch: https://bugzilla.mozilla.org/show_bug.cgi?id=1788911
- Tweetdeck.twitter.com: https://github.com/webcompat/web-bugs/issues/110478 
- Macrumors.com: https://github.com/webcompat/web-bugs/issues/110483

Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1789822
Facebook Container thread: https://github.com/mozilla/contain-facebook/issues/857

**Comment by softvision-raul-bucata** [comment] 2022-09-14 12:09
Issues with Google Calendar. They seem more like a candidate for something breaking with Firefox, as different issues where signaled( mostly UI and some functionalities not working as expected):

Reproducible:
- https://github.com/webcompat/web-bugs/issues/110745
- https://github.com/webcompat/web-bugs/issues/110760

Reported, but not reproducible:
- https://github.com/webcompat/web-bugs/issues/109461
- https://github.com/webcompat/web-bugs/issues/106466

**Comment by softvision-oana-arbuzov** [comment] 2022-09-28 07:17
Users reported issues with Prime videos now playing. We were not able to reproduce them.

- https://github.com/webcompat/web-bugs/issues/110967
- https://github.com/webcompat/web-bugs/issues/110592
- https://github.com/webcompat/web-bugs/issues/110166 
- https://github.com/webcompat/web-bugs/issues/111457 

Found Bugzilla issues:
- https://bugzilla.mozilla.org/show_bug.cgi?id=1612407 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1646683

**Comment by softvision-raul-bucata** [comment] 2022-10-06 08:18
Users reported issues with "Labels" option not functioning in Google Maps. We were able to reproduce the issues.

Reproducible issue:
- https://github.com/webcompat/web-bugs/issues/111546

Duplicates:
- https://github.com/webcompat/web-bugs/issues/111806
- https://github.com/webcompat/web-bugs/issues/111858
- https://github.com/webcompat/web-bugs/issues/111908

**Comment by softvision-oana-arbuzov** [comment] 2022-10-11 13:31
There are some reported issue related to Short YouTube videos - incorrect video played:
- https://github.com/webcompat/web-bugs/issues/111985 - reproducible
- https://github.com/webcompat/web-bugs/issues/111947 - reproducible randomly
- https://github.com/webcompat/web-bugs/issues/112138 - reproducible

Bugzilla: For reference, https://bugzilla.mozilla.org/show_bug.cgi?id=1794103 has been filed.

**Comment by softvision-raul-bucata** [comment] 2022-10-14 07:29
There are some issues where buttons on some pages are not working (mainly the login button):
 - https://github.com/webcompat/web-bugs/issues/112139 -Reproducible
 - https://github.com/webcompat/web-bugs/issues/111336
 - https://github.com/webcompat/web-bugs/issues/111692

**Comment by softvision-raul-bucata** [comment] 2022-10-14 07:30
There are some reported issues regarding the login process on Twitch:
- https://github.com/webcompat/web-bugs/issues/112152
- https://github.com/webcompat/web-bugs/issues/111692
- https://github.com/webcompat/web-bugs/issues/111336

**Comment by sv-calin** [comment] 2022-10-28 13:27
There are some reported issues regarding mail operations not functioning on various email service providers.

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/113069
* https://github.com/webcompat/web-bugs/issues/112719
* https://github.com/webcompat/web-bugs/issues/112485
* https://github.com/webcompat/web-bugs/issues/112330

Reproducible:
* https://github.com/webcompat/web-bugs/issues/112482

**Comment by sv-calin** [comment] 2022-10-28 13:34
Users are complaining that the login process was unsuccessful.

Reproducible:
* https://github.com/webcompat/web-bugs/issues/113057
* https://github.com/webcompat/web-bugs/issues/112754
* https://github.com/webcompat/web-bugs/issues/112735

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/113065
* https://github.com/webcompat/web-bugs/issues/113063
* https://github.com/webcompat/web-bugs/issues/113060
* https://github.com/webcompat/web-bugs/issues/113059
* https://github.com/webcompat/web-bugs/issues/113049
* https://github.com/webcompat/web-bugs/issues/112979
* https://github.com/webcompat/web-bugs/issues/112929
* https://github.com/webcompat/web-bugs/issues/112925
* https://github.com/webcompat/web-bugs/issues/112921
* https://github.com/webcompat/web-bugs/issues/112152
* https://github.com/webcompat/web-bugs/issues/111692
* https://github.com/webcompat/web-bugs/issues/111578
* https://github.com/webcompat/web-bugs/issues/111542
* https://github.com/webcompat/web-bugs/issues/111336


Update 18.11.2022
 Reproducible: 
 * https://github.com/webcompat/web-bugs/issues/114258

**Comment by softvision-raul-bucata** [comment] 2022-10-28 13:34
New reported issues about the video not playing on various platforms:

Reproducible:
* https://github.com/webcompat/web-bugs/issues/112864

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/112995 (Instagram shorts)
* https://github.com/webcompat/web-bugs/issues/112949
* https://github.com/webcompat/web-bugs/issues/112945
* https://github.com/webcompat/web-bugs/issues/112895
* https://github.com/webcompat/web-bugs/issues/112813
* https://github.com/webcompat/web-bugs/issues/112478
* https://github.com/webcompat/web-bugs/issues/113406
* https://github.com/webcompat/web-bugs/issues/113341

**Comment by softvision-raul-bucata** [comment] 2022-10-28 13:36
We have received reports about the burger menu not working on cardmarket.com, thus the login process can not be initiated.

Reproducible:
* https://github.com/webcompat/web-bugs/issues/113057

Duplicates:
* https://github.com/webcompat/web-bugs/issues/113065
* https://github.com/webcompat/web-bugs/issues/113063
* https://github.com/webcompat/web-bugs/issues/113059

**Comment by softvision-raul-bucata** [comment] 2022-11-11 14:38
We have received issues about various buttons not working on certain pages.

Reproducible:
 * https://github.com/webcompat/web-bugs/issues/113715
 *  https://github.com/webcompat/web-bugs/issues/113680

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/113693
* https://github.com/webcompat/web-bugs/issues/113552
* https://github.com/webcompat/web-bugs/issues/113534
* https://github.com/webcompat/web-bugs/issues/113485
* https://github.com/webcompat/web-bugs/issues/113457
* https://github.com/webcompat/web-bugs/issues/113552
* https://github.com/webcompat/web-bugs/issues/113534
* https://github.com/webcompat/web-bugs/issues/113485
* https://github.com/webcompat/web-bugs/issues/113457


Update 18.11.2022:

Reproducible:

* https://github.com/webcompat/web-bugs/issues/114258
* https://github.com/webcompat/web-bugs/issues/113919

**Comment by softvision-raul-bucata** [comment] 2022-11-11 14:43
Issues where videos on pages can not be played:

Reproducible: 

* https://github.com/webcompat/web-bugs/issues/113388

Needsinfo:

* https://github.com/webcompat/web-bugs/issues/113668
* https://github.com/webcompat/web-bugs/issues/113668

Not reproducbile:

* https://github.com/webcompat/web-bugs/issues/113801
* https://github.com/webcompat/web-bugs/issues/113799
* https://github.com/webcompat/web-bugs/issues/113774
* https://github.com/webcompat/web-bugs/issues/113773
* https://github.com/webcompat/web-bugs/issues/113560
* https://github.com/webcompat/web-bugs/issues/113548
* https://github.com/webcompat/web-bugs/issues/113523
* https://github.com/webcompat/web-bugs/issues/113460
* https://github.com/webcompat/web-bugs/issues/113452
* https://github.com/webcompat/web-bugs/issues/113406
* https://github.com/webcompat/web-bugs/issues/113341
* https://github.com/webcompat/web-bugs/issues/113238
* https://github.com/webcompat/web-bugs/issues/113203
* https://github.com/webcompat/web-bugs/issues/113184
* https://github.com/webcompat/web-bugs/issues/113801
* https://github.com/webcompat/web-bugs/issues/113548
* https://github.com/webcompat/web-bugs/issues/113523
* https://github.com/webcompat/web-bugs/issues/113452

**Comment by softvision-raul-bucata** [comment] 2022-11-11 14:46
Also, some pages presented issues with graphics (images, preview, etc).

Reproducible:

* https://github.com/webcompat/web-bugs/issues/113726
* https://github.com/webcompat/web-bugs/issues/113645
* https://github.com/webcompat/web-bugs/issues/113459

Not reproducible/duplicates:

* https://github.com/webcompat/web-bugs/issues/113732
* https://github.com/webcompat/web-bugs/issues/113594
* https://github.com/webcompat/web-bugs/issues/113586
* https://github.com/webcompat/web-bugs/issues/113580
* https://github.com/webcompat/web-bugs/issues/113579
* https://github.com/webcompat/web-bugs/issues/113576
* https://github.com/webcompat/web-bugs/issues/113559
* https://github.com/webcompat/web-bugs/issues/113530
* https://github.com/webcompat/web-bugs/issues/113455

Update 18.11.2022

Reproducible:

* https://github.com/webcompat/web-bugs/issues/113826
* https://github.com/webcompat/web-bugs/issues/114144

**Comment by softvision-raul-bucata** [comment] 2022-11-11 14:48
We have seen some issues where pages presented performance issues,

Reproducible:
* https://github.com/webcompat/web-bugs/issues/113684
* https://github.com/webcompat/web-bugs/issues/113267

Not reproducible:

* https://github.com/webcompat/web-bugs/issues/113795
* https://github.com/webcompat/web-bugs/issues/113575
* https://github.com/webcompat/web-bugs/issues/113555
* https://github.com/webcompat/web-bugs/issues/113535
* https://github.com/webcompat/web-bugs/issues/113230
* https://github.com/webcompat/web-bugs/issues/113535
* https://github.com/webcompat/web-bugs/issues/113230


Update 18.11.2022

Reproducible:

* https://github.com/webcompat/web-bugs/issues/114152

**Comment by sv-calin** [comment] 2022-11-18 14:41
Issues with audio play:

- https://github.com/webcompat/web-bugs/issues/113870
- https://github.com/webcompat/web-bugs/issues/113824

Issue with fullscreen:

- Reproducible: https://github.com/webcompat/web-bugs/issues/114054
- Not reproducible: https://github.com/webcompat/web-bugs/issues/113844

**Comment by sv-calin** [comment] 2022-11-25 14:43
**Issues regarding login.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114450
* https://github.com/webcompat/web-bugs/issues/114258

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/114632
* https://github.com/webcompat/web-bugs/issues/114601
* https://github.com/webcompat/web-bugs/issues/114552
* https://github.com/webcompat/web-bugs/issues/114445
* https://github.com/webcompat/web-bugs/issues/114441


**Issues regarding videoplay.**

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/114586
* https://github.com/webcompat/web-bugs/issues/114547
* https://github.com/webcompat/web-bugs/issues/114536
* https://github.com/webcompat/web-bugs/issues/114533
* https://github.com/webcompat/web-bugs/issues/114309
* https://github.com/webcompat/web-bugs/issues/113668 


**Issues regarding performance.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114597
* https://github.com/webcompat/web-bugs/issues/114283
* https://github.com/webcompat/web-bugs/issues/114278
* https://github.com/webcompat/web-bugs/issues/114152 (duplicate)

**Comment by sv-calin** [comment] 2022-12-02 15:03
**Issues regarding videoplay.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114885

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/114927
* https://github.com/webcompat/web-bugs/issues/114863
* https://github.com/webcompat/web-bugs/issues/114836
* https://github.com/webcompat/web-bugs/issues/114714
* https://github.com/webcompat/web-bugs/issues/114664

**Issues regarding buttons.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114824
* https://github.com/webcompat/web-bugs/issues/114667

**Issues regarding parts of the page not being visible.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114746
* https://github.com/webcompat/web-bugs/issues/114667

**Issues regarding pageload.**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/114794

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/114850
* https://github.com/webcompat/web-bugs/issues/114798

**Comment by softvision-raul-bucata** [comment] 2022-12-09 15:17
We have observed some issues that exhibit graphic glitches (items not fully loading, UI issues, etc).

Reproducible:
* https://github.com/webcompat/web-bugs/issues/115231




Duplicates:

* https://github.com/webcompat/web-bugs/issues/115112
* https://github.com/webcompat/web-bugs/issues/115223
* https://github.com/webcompat/web-bugs/issues/115182

**Comment by softvision-raul-bucata** [comment] 2022-12-16 15:27
We have seen an increase in reported issues about Firefox 110 not being supported.

Reproducible:
* https://github.com/webcompat/web-bugs/issues/115488
* https://github.com/webcompat/web-bugs/issues/115458
* https://github.com/webcompat/web-bugs/issues/115429
* https://github.com/webcompat/web-bugs/issues/115403
* https://github.com/webcompat/web-bugs/issues/115206

**Comment by ksy36** [comment] 2022-12-16 21:39
* https://github.com/webcompat/web-bugs/issues/115206 

is part of Entrata platform (https://github.com/mozilla/webcompat-team-okrs/issues/262#issuecomment-1211521618) for which we ship an intervention, I'll file a bug to add this domain to it (not related to 110, but rather all versions of Firefox)

**Comment by softvision-raul-bucata** [comment] 2022-12-23 12:52
We have seen an increase in the number of issues where video/media is not playing:

Reproducible:
* https://github.com/webcompat/web-bugs/issues/115422

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/115726
* https://github.com/webcompat/web-bugs/issues/115725
* https://github.com/webcompat/web-bugs/issues/115621
* https://github.com/webcompat/web-bugs/issues/115482

Expected:
* https://github.com/webcompat/web-bugs/issues/115649

**Comment by softvision-raul-bucata** [comment] 2022-12-23 12:54
Issues where Azure fails to load elements on the page:

Needsinfo (account needed):

* https://github.com/webcompat/web-bugs/issues/115740
* https://github.com/webcompat/web-bugs/issues/115774

Duplicates:
* https://github.com/webcompat/web-bugs/issues/115826
* https://github.com/webcompat/web-bugs/issues/115767


Update 30.12.2022:

* Thanks to a user that provided us with a test account on https://github.com/webcompat/web-bugs/issues/115740, we were enable to conclude that the issue is a wontfix issue since it only reproduces on the Release version. However, thanks to @ksy36 , a possible uplift in Beta might be in place.

**Comment by softvision-raul-bucata** [comment] 2022-12-23 12:55
Other issues related to graphic glitches:

* https://github.com/webcompat/web-bugs/issues/115800
* https://github.com/webcompat/web-bugs/issues/115783
* https://github.com/webcompat/web-bugs/issues/115754
* https://github.com/webcompat/web-bugs/issues/115714

**Comment by softvision-raul-bucata** [comment] 2022-12-30 12:51
DRM content is needed to be accepted on the first run for video not playing on Netflix, Amazonprime, Disneyplus, Hulu.

This has been addressed initially here: 
* https://github.com/webcompat/web-bugs/issues/116093
* https://github.com/webcompat/web-bugs/issues/116023

**Comment by sv-calin** [comment] 2023-01-06 14:49
**Issues regarding videoplay**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/116339
* https://github.com/webcompat/web-bugs/issues/116301
* https://github.com/webcompat/web-bugs/issues/115422

Not reproducible:
* https://github.com/webcompat/web-bugs/issues/116385
* https://github.com/webcompat/web-bugs/issues/116336

**Issues regarding glitches**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/116380
* https://github.com/webcompat/web-bugs/issues/115915

**Issues regarding performance**

Reproducible:
* https://github.com/webcompat/web-bugs/issues/116276

**Closed as completed** 2023-01-10 13:33 UTC
Labels: Complete
