### ISSUE TITLE
2020Q3 - 4.2 Land ETP shimming in webcompat SAO

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#148] opened 2020-06-29 20:21 UTC
@softvision-oana-arbuzov and @cipriansv will do the QA signoff for the feature.

Carry-over work from https://github.com/mozilla/webcompat-team-okrs/issues/134

The goal here is to land the work from https://bugzilla.mozilla.org/show_bug.cgi?id=1637329, and land as many shims in Q3 as we can.

**Comment by wisniewskit** [comment] 2020-07-06 22:12
I'm just waiting on final r+ from RobWu now on the patch; Dimi has already signed off. I should be able to land as soon as the legal team completes a risk assessment (but that assessment is well underway, and I don't see any major concerns being expressed so far).

Once legal has made a recommendation, we will decide which shims to land right away, and which to wait on for now. I'm presuming that we will land the federated login support for Facebook in strict ETP, and also perhaps some other trivial shims to fix known site breakage on nightly. Then I may investigate opt-ins for other Facebook content, which are at least partially implemented.

It's worth noting that Fenix support is still waiting for [this bug](https://github.com/mozilla-mobile/android-components/issues/6356) to land, and there is also a [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1642468) blocking correct behavior under Fission. It's entirely possible that these will be fixed by the time we finally land, but if not then any necessary follow-up work will be filed as appropriate.

**Comment by wisniewskit** [comment] 2020-07-21 02:58
We received r+, so I tried landing on the past weekend, but there is a mysterious test failure in automation that caused a back-out. It's possible it's just a broken test (it seems flaky already), but I am on PTO this week, so I won't be around to figure it out until next week. RobWu is taking a look, though it seems likely that we won't land it in this cycle unless the test-failure can be covered by Rob or others while I'm away.

On the plus side, Fission and Fenix related fixes have or are landing, so we should be able to create a patch for A-C soon.

**Comment by softvision-oana-arbuzov** [comment] 2020-08-03 15:11
QA testing progress is visible here: https://docs.google.com/spreadsheets/d/1F9vcSpLQ_hNBeZinsytGXlfXpJLW6vh7C0BJYtd9hIY/edit?pli=1#gid=1987467379

**Comment by wisniewskit** [comment] 2020-08-04 13:08
The addon landed, and it seems to have stuck. Now about:compat needs to be fixed, and we need to iterate on improving the addon and landing it on Android.

**Comment by softvision-oana-arbuzov** [comment] 2020-08-05 12:53
We've finished testing Facebook login on the provided sites from [ETP Strict List Breakage Fix Technical Documentation](https://docs.google.com/document/d/1jG94XBGx8iNP89NWInxEtT797g82pCyZqyU5XP2yex0/edit#) and bellow are the issues we found:

[1657330](https://bugzilla.mozilla.org/show_bug.cgi?id=1657330) Unable to login with Facebook on https://fr.boardgamearena.com/ with ETP set to Strict 
[1657332 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1657332) Unable to login with Facebook on https://www.grammarly.com with ETP set to Strict 
[1657334 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1657334 ) Unable to login with Facebook on wish.com with ETP - Strict enabled after signing out 
[1657337 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1657337 ) Unable to login with Facebook on etsy.com with ETP - Strict enabled
[1657342 ](https://bugzilla.mozilla.org/show_bug.cgi?id=1657342 ) Unable to login with Facebook on bloombergquint.com with ETP - Strict enabled

**Comment by wisniewskit** [comment] 2020-08-18 13:08
Only one regression so far, which has been fixed. The code has been backported to the GitHub repo now, as it seems to have stuck for good. Will chat with Steve today to figure out our roadmap here, but otherwise it seems like figuring out the bugs uncovered in the comment above will be the order of the day now.

**Comment by miketaylr** [comment] 2020-08-18 13:15
(Optimistically looking to ride in 82)

**Comment by softvision-oana-arbuzov** [comment] 2020-09-01 12:33
We've came up with a [Feature status](https://docs.google.com/spreadsheets/d/1Y_KDbR5Sb8DcNdcqDFSHt-asY2wmn0t6OLNk_MdLyTw/edit?skip_itp2_check=true#gid=0), [Test Plan](https://docs.google.com/document/d/1w3WNLJbFqcNtPJec1XU2NuoxMJUou75safKCng9Sa20/edit#), [HL Test Case (Desktop)](https://docs.google.com/spreadsheets/d/151fo7n0I1neoBHoDl-JwVH-o7Fhf3nrybKBRHGbqlzA/edit#gid=0) and [Test Report (Desktop)](https://docs.google.com/document/d/1vyAky5XccPK6gJpWAA1twNIkNRVv6oauR7q1akusSr4/edit) documents.  

After our previous update we found new issues:
[1657828](https://bugzilla.mozilla.org/show_bug.cgi?id=1657828) Unable to login with Facebook on datpiff.com with ETP - Strict enabled
[1660443](https://bugzilla.mozilla.org/show_bug.cgi?id=1660443) Unable to login with Facebook on rottentomatoes.com with ETP - Strict enabled
[1661686](https://bugzilla.mozilla.org/show_bug.cgi?id=1661686) Unable to login with Facebook on gradeup.co with ETP - Strict enabled
[1662378](https://bugzilla.mozilla.org/show_bug.cgi?id=1662378) Unable to login with Facebook on voot.com with ETP - Strict enabled

**Comment by wisniewskit** [comment] 2020-09-01 13:07
There is one issue we're trying to deal with right now: https://bugzilla.mozilla.org/show_bug.cgi?id=1661330

Aside from that, i've been in discussions on how to handle the releasee process (blog posts, etc). It seems as though if we find no other blockers, we ought to be alright.

**Comment by miketaylr** [comment] 2020-09-01 13:29
We need to file a new JIRA request for the mobile testing.

**Comment by miketaylr** [comment] 2020-09-02 03:26
https://jira.mozilla.com/browse/PI-794

**Comment by softvision-oana-arbuzov** [comment] 2020-09-02 15:32
We've finished testing ETP Shim on mobile (Android 8 & 10):  
- no new issues were found
- the reported desktop issues also reproduce on mobile

Specific documents were created and updated: [Feature status](https://docs.google.com/spreadsheets/d/1Y_KDbR5Sb8DcNdcqDFSHt-asY2wmn0t6OLNk_MdLyTw/edit?skip_itp2_check=true#gid=0), [Test Plan](https://docs.google.com/document/d/1w3WNLJbFqcNtPJec1XU2NuoxMJUou75safKCng9Sa20/edit#), [HL Test Case (Mobile)](https://docs.google.com/spreadsheets/d/1J1j_RCjG1_la53YTJPiC-6M6oc51yoTmwBzR7p9Uo5c/edit#gid=0) and [Test Report (Mobile)](https://docs.google.com/document/d/1WuLyrxNGpas7QGA4U6Bkd2oRppcD_xHA3p4RRxUJey0/edit)

**Comment by miketaylr** [comment] 2020-09-02 17:02
Thank you @softvision-oana-arbuzov and @cipriansv!

**Comment by wisniewskit** [comment] 2020-09-15 12:57
Quick update: we're likely to slip the release of ETP shims slip into the 83 release instead of 82, due to the UX team wanting some more time to think through the way the ETP "blocked content" interfaces interact with shims. In that case they will continue to be a nightly-only feature during the 82 release cycle.

**Comment by wisniewskit** [comment] 2020-09-29 12:49
We did decide to ship in version 83. I'm just working with Nihanth to figure out what work remains to be done here, and will post another quick update as soon as he has a chance to confirm it.

**Comment by karlcow** [comment] 2021-07-07 03:54
this is probably done.

**Closed as completed by karlcow** 2021-07-07 03:54 UTC
Labels: On Track
