### ISSUE TITLE
2019Q3 - 3.1 Google tier 1 Search Experiment in Fennec

### ISSUE THREAD

**Issue by miketaylr** [mozilla/webcompat-team-okrs#90] opened 2019-07-08 19:39 UTC
* Conduct experiment in Fennec Nightly, spoofing the user agent as Chrome to get Tier 1 Google search.
* <s>Investigate any reported issues and flag core interop bugs with respective engineering teams.</s>

edit: the scope of this kinda changed during the quarter. It evolved into a Fennec experiment, and I think we were hoping to have an analysis done by the end of Q1. We won't get that, but it looks like we did ship it.

**Comment by miketaylr** [comment] 2019-07-09 13:19
@adamopenweb should we ask our SV crew to also do manual testing here? Or do we just want to run the experiment and collect organic bugs?

**Comment by miketaylr** [comment] 2019-07-10 20:56
I chatted with Adam and he recommended we do the following:

* [x] Dig into https://github.com/webcompat/web-bugs/issues/33616, and determine if it's feasible to fix in the experiment addon (and not too much effort)
* [x] Do we have a kill-switch for this? Is there a pref we can Balrog off if things get dicey? (the kill-switch might just be "back it out" since it will be Nightly only)
* [ ] Send an intent email to dev-platform just to give a heads up before we land it
* [ ] Land it (make sure it's behind `FENNEC_NIGHTLY` ifdefs)

**Comment by wisniewskit** [comment] 2019-07-11 16:21
To reply to the second point, the previous version of the addon had an `about:config` preference: `extensions.gws-and-facebook-chrome-spoof.enabled`. So we could flip that pref in Balrog, yes (though we could back it out as well, or just disable it in the relevant `moz.build` file, whatever it easiest).

**Comment by adamopenweb** [comment] 2019-07-11 16:34
Great. The second piece to that is just having the key folks aware, so we can respond quickly if needed.

**Comment by wisniewskit** [comment] 2019-07-16 01:38
Just a quick update: I've got a candidate patch attached to [bz-1566140](https://bugzilla.mozilla.org/show_bug.cgi?id=1566140), and will get that reviewed and send an intent to experiment notice once we're sure we want to deploy this.

**Comment by miketaylr** [comment] 2019-07-26 21:18
Engineering plan for this is here: https://docs.google.com/document/d/1-Op4bXuxA2NCKANmvcfj_beYkCVW5WG7V5Gav63OXoI/edit#

**Comment by adamopenweb** [comment] 2019-08-01 18:48
<s>This KR is currently on hold. </s>

**Comment by wisniewskit** [comment] 2019-08-20 13:07
Work resumed this cycle, and reviews are progressing (and may be done). We're on track to possibly get this in during the next cycle.

**Comment by wisniewskit** [comment] 2019-09-03 13:03
The feature has landed in Fennec nightly, and is set to be enabled in the next release. There are test regressions which may complicate things, but I suspect we have mitigations for that.

**Comment by wisniewskit** [comment] 2019-09-17 12:09
The last cycle was spent putting the finishing touches on this. The final version of the addon (6.0.3) with test-regression fixes has just landed in moz-central, and is due to be uplifted to the ESR and delivered by Balrog as soon as QA gives it their final blessing.

**Comment by wisniewskit** [comment] 2019-09-23 13:18
The code has landed in m-c and is now being delivered to users in Balrog. QA has signed off. From what I can tell, we're ready to roll.

**Comment by miketaylr** [comment] 2019-09-25 16:58
> The code has landed in m-c and is now being delivered to users in Balrog. QA has signed off. From what I can tell, we're ready to roll.

Update: there was a bug in that version, but the latest version (6.1.0) just was cleared for delivery via Balrog https://bugzilla.mozilla.org/show_bug.cgi?id=1583285

**Closed as completed** 2019-10-01 00:38 UTC
Labels: Score: 0.5, Complete

**Comment by adamopenweb** [comment] 2019-10-03 17:44
We hit another problem with Switchboard. Let's call this a 0.5 and it hasn't been deployed yet.
